version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    container_name: froggy-house-jekyll
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --watch --force_polling --host 0.0.0.0 --livereload
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    stdin_open: true
    tty: true